export const UNITY_VS_JSON_ERRATA = [
  "# Creator Works MCP Compatibility Errata",
  "",
  "These source-observed rules override conflicting statements in the supplied Visual Scripting manual below:",
  "",
  "- Unity Visual Scripting 1.9.4 and 1.9.9 serialize nodes and connections together in the canonical `graph.elements` array.",
  "- A node needs a string `$id` only when another serialized element references it. Unity can omit `$id` on unreferenced nodes.",
  "- Visual Scripting 1.9.4 and 1.9.9 omit `$version` on control and value connection elements. Creator Works MCP accepts an omitted connection version or `\"A\"`.",
  "- New Script Graph assets use `Unity.VisualScripting.Flow::Unity.VisualScripting.ScriptGraphAsset` as `m_EditorClassIdentifier` and `NativeFormatImporter` in the asset's `.meta` file.",
  "- An empty string is a valid control-port key. Banter action units such as `SendOneShot`, `SetSpaceStateProp`, and `LoadGltfUrl` deliberately use `\"\"` for their control input and output.",
  "- Event `coroutine` is not always false. Set it to true when a reachable control path enters a wait unit or a coroutine-only loader such as `LoadTextUrl`.",
  "- The manual's blanket warning against direct `Transform` setters is stale. Banter SDK 3.1.2 accepts the world position, world rotation, and local scale member setters used by validated graphs; the selected SDK's own validator remains authoritative.",
  "- Prefer a typed `Literal` value connection for `System.Object` inputs such as `Debug.Log(message)` instead of serializing an incompatible string directly into `%message`.",
  "- In Banter SDK 3.1.2, `LoadTextUrl` maps its `POST` option to `UnityWebRequest.Put`; treat that as an upstream compatibility quirk.",
  "- `validate_vs_graph` checks serialized structure and known Banter types. Unity import validation remains the authority for generic Unity node availability and exact port contracts.",
  "",
  "Observed against Unity 2022.3.39f1 / Visual Scripting 1.9.4 and Unity 6000.3.10f1 / Visual Scripting 1.9.9.",
].join("\n");
